[env:esp32-poe]
platform = espressif32
board = esp32-poe
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs

lib_deps =
  Links2004/WebSockets @ ^2.4.1
  bblanchon/ArduinoJson @ ^6.21.4
